<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="OSIYA" failures="1" tests="1" name="Test" time="17.473" errors="0" timestamp="2023-03-09T09:22:56 IST">
  <testcase classname="test_Classes.LoginPage_TestClass" name="VerifyLoginPageWithInvalidDetails" time="5.523">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index]
at test_Classes.LoginPage_TestClass.VerifyLoginPageWithInvalidDetails(LoginPage_TestClass.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLoginPageWithInvalidDetails -->
  <testcase classname="test_Classes.LoginPage_TestClass" name="VerifyLoginPageWithValidDetails" time="0.0">
    <ignored/>
  </testcase> <!-- VerifyLoginPageWithValidDetails -->
</testsuite> <!-- Test -->
